### ISSUE TITLE
Incorrect account sequence will exist

### ISSUE THREAD

**Issue by bbqaaq** [terra-money/terrain#30]
Seems in previous commit, this problem are marked as solve. But seems my side still experiencing this problem.
But seems the problem is that store code may run a for a period of time, and the reusing the signer account will just outdate.

**Comment by emidev98** [comment]
Hello @bbqaaq, It happens some times when using [validator as signer](https://github.com/terra-money/terrain#deployment). 
Can you try to use a different account to sign the transaction? 
If the issue persists can you share with us a more detailed information like terminal output?

**Comment by bbqaaq** [comment]
Thanks for your support. Yes, Im using validator as signer.
I will try to switch to others user, and see if it gets fixed. If yes, I will close this issue.
