### ISSUE TITLE
Deploy a contract within the task

### ISSUE THREAD

**Issue by deployAt** [terra-money/terrain#34]
Hello,
Is it possible to write a task script that handles a terrain deploy contract command?

```js
const { task, run } = require("@terra-money/terrain");

task(async ({ wallets, refs, config, client }) => {
  // terrain deploy counter --signer test1
});

```

**Comment by emidev98** [comment]
Hello @deployAt should be possible, there is an ongoing initiative to do so. Will keep you updated

**Comment by octalmage** [comment]
This is now possible, see the bottom of this section: 

https://github.com/terra-money/terrain#creating-tasks
