### ISSUE TITLE
Creating new wallet from terrain cli

### ISSUE THREAD

**Issue by laine-ust** [terra-money/terrain#39]
Hi,

I was thinking it would be useful to be able to create / roll a new wallet via the terrain-cli rather than having to use Terra Station or Terra Chrome extension.

Would you accept a PR with such functionality?

**Comment by emidev98** [comment]
Hey @laine-ust , for sure everything that can help terrain users is very welcome. 

Could you explain:
- What does the new functionality do on detail?
- Give three useful examples where users can be benefited?

Thanks!

**Comment by laine-ust** [comment]
> Hey @laine-ust , for sure everything that can help terrain users is very welcome.
> 
> Could you explain:
> 
> * What does the new functionality do on detail?
> * Give three useful examples where users can be benefited?
> 
> Thanks!

Sure, my idea is the following new command:
```
$ terrain wallet:new
```

Which will use terra.js  `new MnemoicKey()` to roll a key. The seed phrase will then be dumped into the console, or into a file specified via a flag `--outfile=./my.key`).

### My usecase

I just setup a separate "secure" Linux laptop that I will use to deploy contract code to mainnet. I need a new wallet for this, and I would like to generate that on the device, and I wish to have as few apps as possible on this device. Therefore I don't have Terra Station nor the Terra wallet. 
Also I like clis :)
