### ISSUE TITLE
[BUG] build failed

### ISSUE THREAD

**Issue by gfijrb** [terra-money/terrain#73]
### Issue description

Can somebody explain what I've missed?)

### Steps to reproduce the issue
1. On execute ```terrain deploy counter --signer test1``` I got next error:

```
....
error[E0425]: cannot find function, tuple struct or tuple variant `Ok` in this scope
   --> /home/piron/.cargo/registry/src/github.com-1ecc6299db9ec823/hex-0.4.3/src/lib.rs:382:5
    |
382 |     Ok(())
    |     ^^ not found in this scope

error: build failed
    Error: Command failed: cargo wasm

```

### Tools and operating system versions
node 16
ubuntu

**Comment by emidev98** [comment]
Hey, can you share the code?

**Comment by gfijrb** [comment]
Lost dependencies install before
