### ISSUE TITLE
[BUG] Dock run error on windows (Cargo.toml)

### ISSUE THREAD

**Issue by ToniBar** [terra-money/terrain#74]
### Issue description
I try to run `npx terrain deploy counter --signer validator` in windows. This fails with error message on $(pwd).

### Steps to reproduce the issue

1. Run `npx terrain deploy counter --signer validator` in windows.
2. Error message: docker: Error response from daemon: create $(pwd): "$(pwd)" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.
    Error: Command failed: docker run --rm -v "$(pwd)":/code         --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target         --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry     
        cosmwasm/rust-optimizer:0.12.5

### Tools and operating system versions

Operating system: windows 10

From what I found the error is caused because windows doesn't recognize $(pwd) and it should be %cd% instead. The `docker -run` call leading to this error can be found under folder /counter in file Cargo.toml. Modifying pwd to cd in this file doesn't work because this file is regenerated after every run. I have for the moment no idea where this generation happens so I am not able to modify pwd.

**Comment by emidev98** [comment]
Hey, thanks for the bug report, as soon as we get some time we'll check it!

**Comment by ToniBar** [comment]
> Hey, thanks for the bug report, as soon as we get some time we'll check it!

I fixed the basename error as well. This is my solution for windows environments: 

`var filename = path.basename(path.resolve(process.cwd()));

            child_process_1.execSync(`docker run --rm -v "%cd%":/code \
        --mount type=volume,source=${filename}_cache,target=/code/target \
        --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
        cosmwasm/rust-optimizer:0.12.5`, { stdio: "inherit" });`

**Comment by octalmage** [comment]
Hey @ToniBar,

sorry for the delay here! Have you tried running Terrain with WSL, or is there a reason why you wouldn't be able to use WSL? In our experience using WSL can avoid these types of issues.

**Comment by octalmage** [comment]
Closing, please reopen if you're still having issues!
