### ISSUE TITLE
[FEATURE] While running "terrain deploy counter --signer test1" got this error

### ISSUE THREAD

**Issue by mandigaaravind** [terra-money/terrain#80]
using pre-baked 'test1' wallet on localterra as signer
    Error: ENOENT: no such file or directory, chdir '/mnt/c/Users/Aravind Mandiga/Downloads/Fullstack/terra/clicker-portal' -> 'contracts/counter'
    Code: ENOENT

I followed all steps correctly still got this error and unable to resolve

**Comment by emidev98** [comment]
Hello, seems like you don't have the counter contract folder under the **contracts** path. Can you double check and confirm please? Also can you check that you have the test1 wallet in keys.terrain.js? Thanks!

**Comment by mandigaaravind** [comment]
Yes I dont have that folder .while "terrain new clicker-portal" it only generated  "clicker-portal" inside contracts folder. May i know how to download counter folder/ what is there inside counter folder?

**Comment by emidev98** [comment]
Then maybe your command should be something like:
```
terrain deploy clicker-portal --signer custom_tester_1
```
Could you try that command and let me know the result please?

**Comment by mandigaaravind** [comment]
custom_test_1 is not working but test1 seems fine ..few files got compiled but it is showing docker error.Can you please check?
and chain is running on other window I used sudo docker-compose up..

using pre-baked 'test1' wallet on localterra as signer
    Finished release [optimized] target(s) in 1.10s
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create": dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.
    Error: Command failed: docker run --rm -v "$(pwd)":/code         --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target         --mount
    type=volume,source=registry_cache,target=/usr/local/cargo/registry         cosmwasm/rust-optimizer:0.12.5

**Comment by emidev98** [comment]
You shouldn't use super user to start docker. 
Please check developers Telegram (https://t.me/+gCxCPohmVBkyNDRl) if you need some more help since this is only related to terrain issue.
Thanks!

**Comment by mandigaaravind** [comment]
I am getting this error while running "terrain deploy counter --signer test1"

storing wasm bytecode on chain... !
    Error: Request failed with status code 400
    Response: unable to resolve type URL /cosmwasm.wasm.v1.MsgStoreCode: tx parse error: invalid request

can you please check?
