### ISSUE TITLE
[BUG] - Terrain console not working on new Terrain template project - macOS M1 Max

### ISSUE THREAD

**Issue by MGabi** [terra-money/terrain#84]
### Issue description
After creating a new project with `terrain new` and running `npm install`, the `terrain console` feature is not working on M1 MAX Macbook

Node version tried:
16.13.2
16.14.2

### Steps to reproduce the issue

1. terrain new testapp
2. cd testapp
3. npm install
4. terrain console -> ERROR

` Error: Cannot find module '/Users/user/Documents/Terra/development/testapp/lib'
    Require stack:
    - /Users/user/.nvm/versions/node/v16.14.2/lib/node_modules/@terra-money/terrain/lib/commands/console.js
    - /Users/user/.nvm/versions/node/v16.14.2/lib/node_modules/@terra-money/terrain/node_modules/@oclif/config/lib/plugin.js
    - /Users/user/.nvm/versions/node/v16.14.2/lib/node_modules/@terra-money/terrain/node_modules/@oclif/config/lib/config.js
    - /Users/user/.nvm/versions/node/v16.14.2/lib/node_modules/@terra-money/terrain/node_modules/@oclif/config/lib/index.js
    - /Users/user/.nvm/versions/node/v16.14.2/lib/node_modules/@terra-money/terrain/node_modules/@oclif/command/lib/command.js
    - /Users/user/.nvm/versions/node/v16.14.2/lib/node_modules/@terra-money/terrain/node_modules/@oclif/command/lib/index.js
    - /Users/user/.nvm/versions/node/v16.14.2/lib/node_modules/@terra-money/terrain/bin/run
    Code: MODULE_NOT_FOUND
`

Even tried to deploy the contract first on LocalTerra, still not working

### Tools and operating system versions

Macbook Pro 16" M1 MAX, 32GB, macOS Monterey 12.4

`$ npm -v && node -v && docker-compose -v && docker -v `
8.5.0
v16.14.2
docker-compose version 1.29.2, build 5becea4c
Docker version 20.10.14, build a224086

**Comment by emidev98** [comment]
Thanks! We appreciate it and we'll check as soon as possible! Cheers!

**Comment by zjhmale** [comment]
@MGabi I think a quick fix is to use the old version of terrain which is `npm install -g @iboss/terrain` instead of `npm install -g @terra-money/terrain`, this works for me like a charm :)

**Comment by emidev98** [comment]
@MGabi can you check with terrain 0.4.1? Thanks

**Comment by MGabi** [comment]
i just get the same `Error: Cannot find module...`
